/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'bhochhi' at '4/9/18 10:56 PM' with Gradle 2.10
 *
 * @author bhochhi, @date 4/9/18 10:56 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
