import java.util.Date;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'bhochhi' at '6/8/18 7:52 AM' with Gradle 2.10
 *
 * @author bhochhi, @date 6/8/18 7:52 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) {
        System.out.println("Hello world");
    }


    //TODO: log me
    public String getDate(int id){
        return new Date().toString();
    }
}
